* External Dependencies:
- authentication
- email domain to institution mapping
- TODO add FICE code to institution table
- searching date fields


* Overview
LSC was interested in way to find, network, and communicate better with peers

Groovy & Grails - practical application to work on while learning

Kevin pull things together.



* https://docs.google.com/document/d/1Boe-UKoDMDgStFxCrR05ovcUUVdnBAS0jejDu_0ugmc/edit?hl=en_US&pli=1

Introduction

The Commons is an online community where SunGard Higher Education
customers, partners, and employees can share experiences, ask
questions, find answers, and connect to a collaborative and informed
network.  The community is built on the edu1world Enterprise Hive
platform to take advantage of the innovative community and
collaboration tools.

A key feature envisioned for the Commons is referred to as the
institutional profile (IP).  The key concept to the IP is to allow
users from one institution to find and connect with users from other
institutions that:

share similar characteristics (e.g., 2 yr, 4 yr, Private, Public,
FTES, Budget, Research, geographic location)

have licensed certain products (e.g., Banner Student, Enrollment
Management, Luminis)

are aspirational peers (e.g., recognized as top 10, best liberal arts
program, size, program offerings).



Customer feedback during the Commons proof of concept pilot has
verified the need and value of this key feature.  Customers have
expressed the desire to connect with other users from
like-institutions to share best practices, tips, implementation
decisions, recommendations, hardware and configurations and so on.

Sample User Stories



 

End User – User Stories:

 

Jane, Director of Admission at an 8,000 FTES community college, wants
to connect with other admissions directors to collaborate on
admissions process improvements to support her school’s new admissions
goals and requirements.  Jane navigates to the institutional profile
module and selects find an institution like mine.  The module returns
a list of closest matches to Jane’s institution (which is derived from
her personal user profile).

Bob, DBA at a 30,000 FTES public research institution, wants to find
other large publics to see if they have experienced worthwhile
performance improvements using RAC.  Bob navigates to the
institutional profile module and selects advance search to query on
characteristics such as FTES > 30,000, Oracle RAC, Sun Hardware.

Carol, Controller at a 5,000 FTES private liberal arts college, is
looking for best-practices for year-end closing.  Carol navigates to
the institutional profile module and selects advance search to query
on characteristics such as FTES ~ 5,000, Banner Finance version 8 and
above, in production for 3 years.

Judy, Vice President of Administration at XYZ College, wants to make
sure the XYZ’s institutional profile data is current.  Judy navigates
to the institutional profile module and finds XYZ’s profile. Judy
wants to change the version of Banner HR to version 8.3 because they
just upgraded.  Because Judy is an employee of XYZ (which is derived
from her personal profile) she is able to edits certain institutional
profile fields.  Judy updates the Banner HR version to 8.3.  Judy also
notes that XYZ College has just changed its name to XYZ University.
The system does not allow Judy to change that protected field.  Judy
clicks on the “contact us” link and sends a note indicating that XYZ’s
name needs to be updated.

Joe, VP of Enrollment Management at XYZ is looking for other customers
using Enrollment Management in a specific geographical area to find
out how other are using BRM. Joe navigates to the institutional
profile module and selects advance search to query on characteristics
such Enrollment Management and selects five states as geographic
locations.

Laura, Product Owner at SGHE wants know how many customers have
implemented the recently released Community Source - Self-Service
PayStub enhancement.  Laura navigates to the profile module and
selects the module PayStub to search for every profile that indicates
they are live or plan to go live.



 

Administrative User – User Stories:

As an administrative user, I need to seed the initial institutional
profiles (e.g., Organization, City, State, Products) from a download
of SunGard’s customer data.

As an administrative user, I need to ...

As an administrative user, I need to ...





 
